name: screl_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta
dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_binding_field: ^0.0.7
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.13

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
